apiVersion: apps/v1
kind: Deployment
metadata:
  name: finalweb
spec:
  selector:
    matchLabels:
      run: finalweb
  replicas: 2
  template:
    metadata:
      labels:
        run: finalweb
    spec:
      containers:
      - name: finalweb
        image: umeshmetkari/finalweb:v1
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: finalweb
  labels:
    run: finalweb
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: finalweb




